name: Build & Release

on:
  push:
    branches:
      - main


jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [self-hosted]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun Packages
        run: bun install

      - name: Install System Packages for Linux (Self-Hosted Only)
        if: matrix.platform == 'self-hosted'
        run: |
          echo "Updating packages"
          sudo apt-get update
          echo "Installing deps (libgtk)"
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Build & Publish Github Release
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "v__VERSION__"
          releaseBody: |
            See the assets to download and install this version.

            If you get a virus warning read this article: https://tauri.by.simon.hyll.nu/concepts/security/false_positives/.

            Windows: Run `attrib -r ftll.msi:Zone.Identifier`.
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          tauriScript: bun tauri
